services:
  konga-database:
    image: postgres:11
    environment:
      POSTGRES_USER: konga
      POSTGRES_DB: konga
      POSTGRES_PASSWORD: konga
    ports:
      - "54330:5432"
    networks:
      - kong-net
    volumes:
      - konga-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U konga"]
      interval: 5s
      retries: 5

  kong:
    image: kong:3.6
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yaml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    networks:
      - kong-net
    volumes:
      - ./kong.yaml:/usr/local/kong/declarative/kong.yaml:Z

  konga:
    image: pantsel/konga:latest
    depends_on:
      konga-database:
        condition: service_healthy
      kong:
        condition: service_started
    environment:
      DB_ADAPTER: postgres
      DB_HOST: konga-database
      DB_USER: konga
      DB_PASSWORD: konga
      DB_DATABASE: konga
    ports:
      - "1337:1337"
    networks:
      - kong-net

networks:
  kong-net:

volumes:
  konga-db-data:
